### ISSUE TITLE
KeyError: 'features.conv4.weight'

### ISSUE THREAD

**Issue by wangchao0899** [Heonozis/FaceShifter-pytorch#2]
Hi，when I test Demo，I got a Error~
 
 File "D:\FaceShifter-pytorch\face_modules\mtcnn_pytorch\src\get_nets.py", line 102, in __init__
    p.data = torch.FloatTensor(weights[n])
KeyError: 'features.conv4.weight'

**Comment by Heonozis** [comment]
Let me upload the latest weights to cloud it seems weights are outdated

**Comment by Heonozis** [comment]
@wangchao0899 please refer updated https://github.com/Heonozis/FaceShifter-pytorch#demo section and see updated weights

**Comment by wangchao0899** [comment]
![image](https://user-images.githubusercontent.com/53893157/81472086-3b551400-9228-11ea-873d-d68491922cc3.png)

oh~No~
Whether I use old or new pertrain weights, when I run python demo_cam.py.
throw the same Error

Traceback (most recent call last):
  File "D:/FaceShifter-pytorch/demo_cam.py", line 27, in <module>
    detector = MTCNN()
  File "D:\FaceShifter-pytorch\face_modules\mtcnn.py", line 15, in __init__
    self.rnet = RNet().to(device)
  File "D:\FaceShifter-pytorch\face_modules\mtcnn_pytorch\src\get_nets.py", line 102, in __init__
    p.data = torch.FloatTensor(weights[n])
KeyError: 'features.conv4.weight'

**Comment by wangchao0899** [comment]
@Heonozis 
Great！ It works~
